// examples/frameworks/nuxt/app/pages/signup.vue
<script setup lang="ts">
// `useAnalytics` is auto-imported by `@typetrack/nuxt`'s module (`addImports`,
// `packages/nuxt/src/module.ts`) -- no explicit import line needed in a real
// Nuxt app. Shown as an explicit import here only because this file lives
// outside of a real Nuxt build's auto-import scanning.
import { useAnalytics } from "@typetrack/nuxt";

interface SignUpEvents {
  "User Signed Up": { plan: "free" | "pro" };
}

const analytics = useAnalytics<SignUpEvents>();
const email = ref("");
const submitted = ref(false);

function handleSubmit(): void {
  if (!email.value.includes("@")) return;

  void analytics.identify(email.value, { plan: "free", source: "signup_form" });
  void analytics.track("User Signed Up", { plan: "free" });
  submitted.value = true;
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input v-model="email" type="email" name="email" placeholder="you@example.com" />
    <button type="submit">Sign up</button>
    <p v-if="submitted" class="confirmation">Thanks for signing up!</p>
  </form>
</template>

// examples/frameworks/remix/app/routes/signup.tsx
import { useState } from "react";
import { useAnalytics } from "@typetrack/remix";

interface SignUpEvents {
  "User Signed Up": { plan: "free" | "pro" };
}

// A realistic route component: reads `useAnalytics()` (re-exported,
// unmodified, from `@typetrack/react` -- see `packages/remix/src/index.ts`'s
// own header comment) and fires `identify()` + `track("User Signed Up",
// ...)` on submit.
export default function SignUp() {
  const analytics = useAnalytics<SignUpEvents>();
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);

  function handleSubmit(event: React.FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    if (!email.includes("@")) return;

    void analytics.identify(email, { plan: "free", source: "signup_form" });
    void analytics.track("User Signed Up", { plan: "free" });
    setSubmitted(true);
  }

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="email"
        name="email"
        placeholder="you@example.com"
        value={email}
        onChange={(event) => setEmail(event.target.value)}
      />
      <button type="submit">Sign up</button>
      {submitted ? <p className="confirmation">Thanks for signing up!</p> : null}
    </form>
  );
}
